### ISSUE TITLE
Server side

### ISSUE THREAD

**Issue by edgarreis** [boseji/xxtea-lib#1]
Hi,
I'm working on ESP8266 (using .ino) and I need encrypt my data to send to MQTT broker. 
I'm trying use this library to encrypt my payload, but I don't know how decrypt on my server side (written on python, js, ruby,...). 
what bases I need to have on my algorithms? 
you've done it ever?

Thank you in advance,

**Comment by boseji** [comment]
As suggested by @ThePacemaker in one more the #2 you can use this site:
https://www.tools4noobs.com/online_tools/xxtea_encrypt/
https://www.tools4noobs.com/online_tools/xxtea_decrypt/
They use a websocket based interface.
