### ISSUE TITLE
XXTEA ESP32 + PHP server

### ISSUE THREAD

**Issue by GIOTLAB** [boseji/xxtea-lib#12]
Hi,
I want to make an encrypted communication between esp32 and my PHP server (ESP32 encrypt, PHP decrypt and vice versa). When I encrypt "HELLO WORLD" on my esp with the key "ENCRYPTION KEY" I get this: 35bd3126715874f741518f4d and when I encrypt it on my PHP server I get this: T1YNYC4P4R2Y5eCxUqtjuw==. 
How can I make the results the same?
(I'm using this PHP library: https://github.com/xxtea/xxtea-php)

**Comment by boseji** [comment]
Repeat request for #5
