### ISSUE TITLE
Example with two keys raw enc/dec in the same project needed

### ISSUE THREAD

**Issue by vtomanov** [boseji/xxtea-lib#13]
The raw options and  to have two different encryption keys in the same sketch is not possible ? 

e.g. in one sketch I need to encrypt two different streams with different keys

**Comment by ofthesea-io** [comment]
So I assume you have encrypted the data with the two different keys and then used the same decryption keys to decrypt the data... with the correct corresponding encryption key?

**Comment by boseji** [comment]
Please look at the dual key example:
https://github.com/boseji/xxtea-lib/tree/master/examples/xxtea_Easy-2key

This library in now under active development for fixes and extensions.

**Comment by boseji** [comment]
Example included so closing the issue
