### ISSUE TITLE
How to change the output of encrypted text to Base64?

### ISSUE THREAD

**Issue by EuphoriaCelestial** [boseji/xxtea-lib#16]
I tried your example code, it work fine, but the encrypted text is in HEXA (I guess)
My server side can only work with Base64, how can I change the output to Base64?

![image](https://user-images.githubusercontent.com/43977734/56459689-58226d80-63c1-11e9-9776-ab9099a4278c.png)

**Comment by ofthesea-io** [comment]
You can Base64 the text on the IoT device,  then encrypt the Base64 with XXTEA  and then of the server decrypt it back into Base64?

**Comment by EuphoriaCelestial** [comment]
No, it not work like that. The input is String here, but it convert to hexa in the library

**Comment by ofthesea-io** [comment]
The String object is just a wrapper object around a char array. I would try
and stay away from the String object  and just work with the base char
stream.

**Comment by boseji** [comment]
@VisualSanity , you are right. Some times the repeated allocation in MCUs can cause fragmentation and corrupt the memory. Its better to use use the Native interface `xxtea`.

@EuphoriaCelestial Try to look at the Raw example :
https://github.com/boseji/xxtea-lib/tree/master/examples/xxtea_Raw

Hope you can get the Char Array that's binary and then use a Base64 converter to generate your stream.
You can also look at another project 
https://github.com/boseji/rBASE64/tree/master/examples/base64-generic
For how to use a Base64 converter.
