### ISSUE TITLE
XXTEA implement in other languages return different key

### ISSUE THREAD

**Issue by clydde** [boseji/xxtea-lib#17]
Hi, I have a problem, the lib is very fast and easy to implement, but I need read a crypted text created in XXTEA  JavaScript lib,  The JS lib and other languages no return the same key that this library. 

Its very difficult implement this algorim in other languages? 
Now need JavaScript, but being able tomorrow will be .NET

I found this, though - XXTEA implement in other languages but return different key :(
https://github.com/xxtea

Thank you very much for your time!

**Comment by boseji** [comment]
This implementation follows the littlendian for of memory alignment.
And stream bit fragmentation. 

Some correlation to algorithms here:

1. For Javascript follow this implementation: http://www.movable-type.co.uk/scripts/tea-block.html

2. For Golang follow this implementation: https://github.com/hillu/go-xxtea

Different implementation yield different results.
