### ISSUE TITLE
xxtea arduino library and javascript

### ISSUE THREAD

**Issue by mysecondnameis** [boseji/xxtea-lib#19]
Dear Sir,
I found the difference between encrypt results between arduino library and javascript
and it causes a difference in the decrypt result, thanks

**Comment by boseji** [comment]
Hi,

Please read the documentation on **Javascript XXTEA** implementations.
https://github.com/boseji/xxtea-lib#javascript

We use the little-endian 8-bit memory format any other format of representation are not supported.

Refer the Issue #17
