### ISSUE TITLE
Decrypt function doesn't work in both examples

### ISSUE THREAD

**Issue by pinkfloyd11** [boseji/xxtea-lib#3]
Decrypt function doesn't work in both examples.

**Comment by boseji** [comment]
What platforms are you trying this on ?
It's tested on Arduino Uno, Arduino Mega, Arduino Zero and ESP8266.

**Comment by boseji** [comment]
Still waiting for response. Else we would have to close this issue request.

**Comment by pinkfloyd11** [comment]
Sorry for delay.
We are testing on arduino uno.
Thanks

**Comment by boseji** [comment]
It does work there, will add the travis CI for this just in case.
Please explain how and what is not working.

**Comment by boseji** [comment]
Release Update,
Also tested for ed651de and found working without issues on Arduino Uno.
