### ISSUE TITLE
Decrypt string from external source

### ISSUE THREAD

**Issue by ofthesea-io** [boseji/xxtea-lib#4]
Hi boseji

I have been using your rBase64 and xxtea libs. If I try and decrypt a string from an external source that has been encrypted and base64, the decryption fails. 

If you run the code below, I get the following repsonse:

![image](https://user-images.githubusercontent.com/8189997/28376640-8a38e8fc-6ca2-11e7-8218-fe2496acec3f.png)

#include <xxtea-iot-crypt.h>
#include <rBase64.h>

void setup() 
{
  Serial.begin(115200);

  String tmp = "BEFE2E575734E6B854245F7BC9SGT";
  xxtea.setKey("9DJK25D57C91FBB");
  
  // Encrypt the string and base64 encode it
  String raw = xxtea.encrypt(tmp);
  String encoded = rbase64.encode(raw);

  Serial.print("encrypt raw : ");
  Serial.println(raw);

  Serial.print("encrypt encoded : ");
  Serial.println(encoded);

  String decrypted_raw = xxtea.decrypt(raw);

  // first decoded the string then decrypt it
  String decoded = rbase64.decode(encoded);
  String decrypted_encoded = xxtea.decrypt(decoded);

  Serial.print("Decrypted raw : ");
  Serial.println(decrypted_raw);

  Serial.print("Decrypted encoded : ");
  Serial.println(decrypted_encoded);

  //Take the tmp string from above and encrypt and base64 it on https://www.tools4noobs.com/online_tools/xxtea_encrypt/

  String tools4noobs_raw = "WEW4D1NIJSUeQQxvfV2vIV8i2g0ZraSUTdgTsdvRZ91qJJtv"; // tools4noobs response
  String tools4noobs_decrypt_raw = xxtea.decrypt(tools4noobs_raw);
  String tools4noobs_decoded = rbase64.decode(tools4noobs_raw);
  String tools4noobs_decoded_decrypt = xxtea.decrypt(tools4noobs_decoded);

  Serial.print("tools4noobs decoded : ");
  Serial.println(tools4noobs_decoded);

  Serial.print("tools4noobs decrypt raw : ");
  Serial.println(tools4noobs_decrypt_raw); // should fail

  Serial.print("tools4noobs decoded decrypted : ");
  Serial.println(tools4noobs_decoded_decrypt); // Should pass

  Serial.println("Done!");
}

void loop() {

}

I ran the code on a ESP8266 12e NodeMCU board. 

Sorry about the first post. I'm sure it made no sense. :~)

**Comment by ofthesea-io** [comment]
Please see original post. I have updated it.

**Comment by boseji** [comment]
This is similar to the earlier problems. 
Please do not use "https://www.tools4noobs.com/online_tools/xxtea_encrypt/"

They have a completely diffrent way of encryption.
The method used in this library is based around a 80byte or 640bit boundary.
It does not follow the custom chunking done in the mentioned website.

Please use the Golang script provided in the documentation.

**Comment by ofthesea-io** [comment]
Hi boseji

Do you know of a server side library that works with your library, besides the Golang that is provided in the documentation?

**Comment by boseji** [comment]
Sorry I don't know currently any one using this encryption.
Use Golang server it works well with the native Crypto wrappers.
Its all about the data width. May be you can modify this code to suit your requirement.
Its open source under CC-BY-SA, please use freely.

**Comment by boseji** [comment]
Looks like you had some things earlier too https://github.com/boseji/xxtea-iot-crypt/issues/2
So closing this one also.
