### ISSUE TITLE
Crypting LoRa communications

### ISSUE THREAD

**Issue by BlackxRyan** [boseji/xxtea-lib#6]
Hi.

First, thanks for the library, the code is not too complex and it works well.

I want to use it to secure communication between two Heltec WiFi LoRa 32 ESP32 + OLED modules, a sender and a receiver. These use a technology simlar to the phones. For the moment, I'm sending simple messages.

![image](https://user-images.githubusercontent.com/36700904/37658621-479f7bb6-2c4e-11e8-950e-5d70cdc147fa.png)

Using the RAW and LoRa exemples, I made a code but I doesn't decrypt the data. In fact, I don't know how to order the commands to decrypt the received message.

LoRa library I'm using : https://github.com/sandeepmistry/arduino-LoRa

LoRa Sender
```
#include <LoRa.h>
#include <xxtea-iot-crypt.h>

#define BAND    868E6  //you can set band here directly,e.g. 868E6,915E6
#define PABOOST true

int counter = 0;

String message;

void setup() {
  pinMode(25,OUTPUT);
  
  Serial.begin(115200);
  while (!Serial);
  Serial.println("LoRa Sender");

  LoRa.begin(BAND,PABOOST);
}

void loop() {
  
  uint8_t keybuf[] = "password";
  uint8_t plaintext[] = "Hello";
  uint8_t buffer[200];
  size_t len = 200, i;

  // Setup the Key - Once
  if(xxtea_setup(keybuf, strlen((char *)keybuf)) != XXTEA_STATUS_SUCCESS) {
    Serial.println(" Assignment Failed!");
    return;
  }

  // Perform Encryption on the Data
  len = 200;  // - Initialize the Maximum buffer length
  if(xxtea_encrypt(plaintext, strlen((char*)plaintext), buffer, &len) != XXTEA_STATUS_SUCCESS) {
    Serial.println(" Encryption Failed!");
    return;
  } else {
    Serial.println(" Encrypted Data");
    for(i = 0;i<len;i++)
      message = String (buffer[i], HEX);
    Serial.println();
  }
  
  Serial.print("Sending packet: ");
  Serial.println(counter);
  // send packet
  LoRa.beginPacket();
  LoRa.print(message);
  LoRa.print(counter);
  LoRa.endPacket();
  
  counter++;

  delay(2000);
}
```

LoRa Receiver
```
#include <LoRa.h>
#include <xxtea-iot-crypt.h>

#define BAND    868E6  //you can set band here directly,e.g. 868E6,915E6
#define PABOOST true

String message;

void setup() {
  Serial.begin(115200);
  while (!Serial); //test this program,you must connect this board to a computer
  Serial.println("LoRa Receiver");
  LoRa.begin(BAND,PABOOST );
}

void loop() {
  uint8_t keybuf[] = "password";
  uint8_t buffer[200];
  size_t len = 200, i;

  xxtea_setup(keybuf, strlen((char *)keybuf));
  
  // try to parse packet
  int packetSize = LoRa.parsePacket();
  if (packetSize) {
    // received a packet
    Serial.print("Received packet '");
    // read packet
    while (LoRa.available()) {
      message = (char)LoRa.read();
      xxtea_decrypt(buffer, len);
      Serial.print((char *)buffer);
    }
    // print RSSI of packet
    Serial.print("' with RSSI ");
    Serial.println(LoRa.packetRssi());
  }
}

```

The result :
![image](https://user-images.githubusercontent.com/36700904/37658780-9a5ab898-2c4e-11e8-82fd-9c0dbd29db65.png)

**Comment by boseji** [comment]
***Great work !***

Its nice to see the library has been useful to you.

Yes there is particular way in which the bit streams need to be encoded.

Let me point you to the exact portion of the code.

https://github.com/boseji/xxtea-iot-crypt/blob/master/src/xxtea-iot-crypt.cpp#L97

This is where the Low-level function actually encrypts the package.

Now to understand this lets look at an Array of bytes and how the Encryption algorithm handles it:
```c
uint8_t arr[8] = { 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08};
```

Now when we pass it to the Encryption Function it becomes:
```c
uint32_t arr[2] = { 0x04030201, 0x08070605};
```

This is what the line above does:
```c
memcpy((void *)xxtea_data, (const void *)data, len);
```
This copies the Byte array into a 32bit data array.

You can manipulate this part of the Library to find out how the encoding is going on.

Also one more suggestion from my side would be - encode the data to Base64 using another arduino library. 

That might help to avoid the encoding mismatch. Since after encryption the data becomes binary and can't be handled as character array any more.

I am myself trying to solve this problem since PHP implementation does have issues due to this non-aligned conversion.

Hope this helps.

**Comment by BlackxRyan** [comment]
Thanks for the quick answer. I understand better how the function works now.

I just have to find a way to use "(char)LoRa.read()" and "(char *)buffer" together to decrypt the message.

I'm going to study that and I'll keep you informed.

**Comment by BlackxRyan** [comment]
I studied your other [library](https://github.com/boseji/rBASE64). It works fine and I finally found a way to stock the LoRa.read() chars in a string. I declare "char string[32];" and I use "string[i] = (char)LoRa.read();" in the "for" to stock it.

Now I have to use this code with the xxtea library right ?

Here's the code :

LoRa Sender (64)

```
#include <LoRa.h>
#include <rBase64.h>

rBase64generic<250> mybase64;

#define BAND    868E6  //you can set band here directly,e.g. 868E6,915E6
#define PABOOST true

int counter = 0;

String message;

void setup() {
  pinMode(25,OUTPUT);
  
  Serial.begin(115200);
  while (!Serial);
  Serial.println("LoRa Sender");
  
  LoRa.begin(BAND,PABOOST);
}

void loop() {

  mybase64.encode("Hello");
    
  Serial.print("Sending packet: ");
  Serial.println(counter);
  
  LoRa.beginPacket();
  LoRa.print(mybase64.result());
  LoRa.endPacket();
  
  counter++;

  delay(2000);
}
```

LoRa Receiver (64)
```
#include <LoRa.h>
#include <rBase64.h>

rBase64generic<250> mybase64;

#define BAND    868E6  //you can set band here directly,e.g. 868E6,915E6
#define PABOOST true

char string[32];

void setup() {
  Serial.begin(115200);

  Serial.println("LoRa Receiver");
  LoRa.begin(BAND,PABOOST );
}

void loop() {
  
  int packetSize = LoRa.parsePacket();
  if (packetSize) {
    // received a packet
    Serial.print("Received packet '");
    // read packet
    for (int i = 0; i < packetSize; i++)
  {    
     string[i] = (char)LoRa.read();
  }
    mybase64.decode(string);
    Serial.println(mybase64.result());
    // print RSSI of packet
    Serial.print("' with RSSI ");
    Serial.println(LoRa.packetRssi());
  }
}
```

**Comment by boseji** [comment]
***Great Work!***

However I could not find where the XXTEA is being used.
Since base64 is only encoding not encryption.

Thanks for mentioning the [rBase64](https://github.com/boseji/rbase64), I got that right this time.
Yes it definitely helps to encode and send out the data.
Since I figured out the String allocation isn't actually helping.

So I had the *rBase64* api changed completely. To make it work.

May be I need to provide some thing similar for the XXTEA also.
It would nice to convert the `class xxtea_c` to a bounded generic C++ . 
However my new changes are going to be a separate class of its own.
Since you are using this library, I will keep the Core API intact and provide a separate generic class in the next update.

Hope that I can close the issue now.

Let me know.

**Comment by BlackxRyan** [comment]
So I tried to use xxtea with Base64 but it doesn't work.

What are you suggesting me ?

LoRa Sender xxtea (64)
```
#include <LoRa.h>
#include <xxtea-iot-crypt.h>
#include <rBase64.h>

rBase64generic<250> mybase64;

#define BAND    868E6  //you can set band here directly,e.g. 868E6,915E6
#define PABOOST true

int counter = 0;

char cryptedtext[32];
char string[32];

String message;

void setup() {
  pinMode(25,OUTPUT);
  
  Serial.begin(115200);
  while (!Serial);
  Serial.println("LoRa Sender");
  
  LoRa.begin(BAND,PABOOST);
}

void loop() {
  
  uint8_t keybuf[] = "securitykey";
  uint8_t plaintext[] = "Hello";
  uint8_t buffer[200];
  size_t len = 200, i;
  
  // Setup the Key - Once
  if(xxtea_setup(keybuf, strlen((char *)keybuf)) != XXTEA_STATUS_SUCCESS) {
    Serial.println(" Assignment Failed!");
    return;
  }

  // Perform Encryption on the Data
  len = 200;  // - Initialize the Maximum buffer length
  if(xxtea_encrypt(plaintext, strlen((char*)plaintext), buffer, &len) != XXTEA_STATUS_SUCCESS) {
    Serial.println(" Encryption Failed!");
    return;
  } else {
    for(i = 0;i<len;i++)
       cryptedtext[i] = ((char)buffer[i], HEX);
    Serial.println();
  }
  
  mybase64.encode(cryptedtext);
    
  Serial.print("Sending packet: ");
  Serial.println(counter);

  LoRa.beginPacket();
  LoRa.print(mybase64.result());
  LoRa.endPacket();
  
  counter++;

  delay(2000);
}
```

LoRa Receiver xxtea (64)
```
#include <LoRa.h>
#include <xxtea-iot-crypt.h>
#include <rBase64.h>

rBase64generic<250> mybase64;

#define BAND    868E6  //you can set band here directly,e.g. 868E6,915E6
#define PABOOST true

String message;

char string[32];

void setup() {
  Serial.begin(115200);
  while (!Serial); //test this program,you must connect this board to a computer
  Serial.println("LoRa Receiver");
  LoRa.begin(BAND,PABOOST );
}

void loop() {
  uint8_t keybuf[] = "Abprod";
  uint8_t buffer[200];
  size_t len = 200, j;

  xxtea_setup(keybuf, strlen((char *)keybuf));
  
  // try to parse packet
  int packetSize = LoRa.parsePacket();
  if (packetSize) {
    // received a packet
    Serial.print("Received packet '");
    // read packet
    for (int i = 0; i < packetSize; i++)
  {    
     string[i] = (char)LoRa.read();
     mybase64.decode(string); 
     for(int j = 0;j<len;j++)
      Serial.print(buffer[j], HEX);
    Serial.println();     
  }
  if(xxtea_decrypt(buffer, len))
      {
        Serial.print((char *)buffer);     
      }
    // print RSSI of packet
    Serial.print("' with RSSI ");
    Serial.println(LoRa.packetRssi());
  }
}
```

**Comment by boseji** [comment]
Can you detail whats failing ?

Its not possible to replicate lora communications on my side.
Best would be simpler example where two arduinos are talking to each other.

**Comment by BlackxRyan** [comment]
It's failing when I try to decode and then decrypt. That's the hardest part I think, I must order the commands correctly.

It's this part : 

```
for (int i = 0; i < packetSize; i++)
  {    
     string[i] = (char)LoRa.read();
     mybase64.decode(string); 
     for(int j = 0;j<len;j++)
{
     Serial.print(buffer[j], HEX);   
 }
 }
  if(xxtea_decrypt(buffer, len))
      {
        Serial.println((char *)buffer);     
      }
```

It prints this : 

![image](https://user-images.githubusercontent.com/36700904/37721303-70eccf56-2d29-11e8-878d-ed5585f00a47.png)

**Comment by BlackxRyan** [comment]
Here's the simple exemples. You can find the LoRa library here : https://github.com/sandeepmistry/arduino-LoRa

LoRa Sender
```
#include <SPI.h>
#include <LoRa.h>

#define BAND    868E6  //you can set band here directly,e.g. 868E6,915E6
#define PABOOST true

void setup() {
  pinMode(25,OUTPUT);
  
  Serial.begin(115200);

  Serial.println("LoRa Sender");
  
  LoRa.begin(BAND,PABOOST);
}

void loop() {
  Serial.print("Sending packet: ");
  // send packet
  LoRa.beginPacket();
  LoRa.print("hello ");
  LoRa.endPacket();
}
```


LoRa Receiver
```
#include <SPI.h>
#include <LoRa.h>

#define BAND    868E6  //you can set band here directly,e.g. 868E6,915E6
#define PABOOST true
void setup() {
  Serial.begin(115200);
  while (!Serial); //test this program,you must connect this board to a computer
  Serial.println("LoRa Receiver");
  LoRa.begin(BAND,PABOOST );
}

void loop() {
  // try to parse packet
  int packetSize = LoRa.parsePacket();
  if (packetSize) {
    // received a packet
    Serial.print("Received packet '");
    // read packet
    while (LoRa.available()) {
      Serial.print((char)LoRa.read());
    }
    // print RSSI of packet
    Serial.print("' with RSSI ");
    Serial.println(LoRa.packetRssi());
  }
}
```

**Comment by boseji** [comment]
I am sorry we are going off-topic here.
This library can't help you with your specific application.
Having said that, I would request you to send the encrypted and decrypted output from the XXTEA library.
Only upon that I can divine what going wrong in the XXTEA.

**Comment by BlackxRyan** [comment]
No problem. You already helped me a lot, thanks.

I'm going to study that with my colleague.
